version: '3.3'

services:
  load_balancer_1:
    image: custom-load-balancer:latest
    network_mode: "host"
    ports:
    - "8080:8080"  # Maps host port 8081 to container port 8080

  load_balancer_2:
    image: custom-load-balancer:latest
    network_mode: "host"
    ports:
    - "8085:8080"  # Maps host port 8082 to container port 8080

