FROM gcc:latest

# Set the working directory in the container
WORKDIR /app

# Install necessary packages
RUN apt-get update && \
    apt-get install -y cmake make g++

# Copy all source files to the container
COPY . /app

# Compile the server code
RUN g++ -std=c++17 -pthread -o server server1.cpp BaseServer.cpp

# Expose the port
EXPOSE 8084
EXPOSE 8082
EXPOSE 8083

# Command to run the server
CMD ["./server"]

